# Generated by Django 5.2.6 on 2025-10-01 00:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, verbose_name='Статус')),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('description', models.TextField(verbose_name='Описание')),
                ('formula', models.CharField(verbose_name='Химическая формула')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
                'db_table': 'elements',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Введён'), (2, 'В работе'), (3, 'Завершен'), (4, 'Отклонен'), (5, 'Удален')], default=1, verbose_name='Статус')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('date_formation', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('date_complete', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderator', to=settings.AUTH_USER_MODEL, verbose_name='Профессор')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Расчет расстворимости',
                'verbose_name_plural': 'Расчеты расстворимости',
                'db_table': 'calculations',
                'ordering': ('-date_formation',),
            },
        ),
        migrations.CreateModel(
            name='ElementCalculation',
            fields=[
                ('pk', models.CompositePrimaryKey('element_id', 'calculation_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('temperature', models.IntegerField(default=0)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.calculation')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.element')),
            ],
            options={
                'verbose_name': 'м-м',
                'verbose_name_plural': 'м-м',
                'db_table': 'element_calculation',
                'ordering': ('pk',),
            },
        ),
    ]
